blog/urls.py
from django.urls import path

from blog import views
#importing the views.py from the portfolio

#inorder to access the blog title with likable link, we add this 
#
app_name = 'blog'
#

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.details, name = 'details'),
#if you get an integer, pass to views.detail with method 'details'
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from portfolio import views
#importing the views.py from the portfolio

urlpatterns = [
    path('admin/', admin.site.urls),
        
    path('', views.home, name = 'home'),
    
    path('blog/', include('blog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length = 200)
    
    description = models.TextField()
    
    date = models.DateField()
    
    def __str__(self):
        return self.title
#this is because, in admin/ page, to veiw the actual blog name in the outline

portfolio/models.py
from django.db import models

class Project(models.Model):
#take the reference form the Django 'model Feild type' from the online source
    title = models.CharField(max_length = 100)
    
    description = models.CharField(max_length = 250)
    
    image = models.ImageField(upload_to='portfolio/images/', blank = True)
    
    url = models.URLField(blank=True)
    
    #the blank=True will allow the feild to be left blank
    #Flase, if it is left blank, it would raise an error

    def __str__(self):
        return self.title

#for making the project name dislayed in the admin/ 
    
    

blog/views.py
from django.shortcuts import get_object_or_404


from django.shortcuts import render
from .models import Blog

def all_blogs(request):

#we did the {{blog.count}} in the all_blog.html file, but that will show the clogs that are present 
#that will not taken the remaining hidden (outdated) blogs 
#-------man, i thought of writing a program for this, but i have no idea ---- so remove [:5]
    blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date')
    #ordering the blog and getting the last 5 blogs only
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def details(request, blog_id):

#to take 1 particular blog, import get_ibject_or_404
    blog = get_object_or_404(Blog, pk = blog_id)
#grab the number and display the corresponding blog_id
    return render(request, 'blog/details.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    #shifting the database to web,
    return render(request, 'portfolio/home.html', {'projects':projects})
#all the Porject class codes from the models.py is imported and sent to portfolio/home.html 
#and with disctionary 'projects' : with passowrd 'projects'
  

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}
<!--above is for template-->

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<!--To show no of bolgs-->
<h3 class="text-center mb-5">Jerlshin has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:details' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/details.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!--CSS bootstrap-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <!-- This is to make the logo available in the "tab" of website-->
    <link rel="icon" type="image/png" href="{% static "portfolio/images2.png" %}">

    <title>JG_portfolio</title>
  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static "portfolio/images2.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
          <span>Jerlshin</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.lkedin.com/in/jerlshin-j-g-9748b9264/" target="_blank">LinkedIn</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
            </li>
            <!--in a <a> tag, mention "target" to move to next link in next page-->
            <li>
              <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  
  </html>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}<!-- Without this, you cant import the files from the static-->

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/image1.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Hey.. page is under cOnsTRuCtIOn... <strong>...Testing...</stron> 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    
<!--If the project.url exit, then display the a tag, else skip
similar to the if loop -->
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}